### PR TITLE
feat: ✨ Added .triggerFocus() method

### PR DESCRIPTION
**Pull request by Dmitry-GH**
Hi!
First of all, thanks for such a wonderful lib!

I just need the ability to trigger .focus() when I show your component in my project (in UI it hidden on init).

This code works for me.

Feel free to suggest a better naming or request some changes in my PR.

Thanks!

### CODE REVIEW

**Comment by Karthik-B-06** [comment]
Hey @Dmitry-GH , would it be simpler if we have a method as a `refCallback` returning a ref of the TextInput which can be used to set focus, blur and all other actions?

**Comment by Dmitry-GH** [comment]
Hey @Karthik-B-06 , thanks for response, your idea sounds more versatile.

Did you mean something like that?

```js
useImperativeHandle(ref, () => ({
  searchInputRef() {
    return searchTextInput;
  },
}));
```

and then use it like this

```js
const searchInput = useRef();
[...]
useEffect(() => {
  if (isSearchComponentVisible) {
    searchInput.current.searchInputRef().focus();   <--here
  }
}, [isSearchComponentVisible]);
<SearchComponent
  value={searchTerm}
  theme={theme}
  onChange={onChange}
  onSearchClear={onSearchClear}
  ref={searchInput}
/>

```

**Comment by Karthik-B-06** [comment]
Yes, @Dmitry-GH. Something like that. Just make sure the component works fine using the example app. Let me see if there is a better way to achieve it.

**Comment by Dmitry-GH** [comment]
Hi @Karthik-B-06  👋
I made changes to the component and updated the example app.
Checked on iOS and Android, works fine.

**Comment by Karthik-B-06** [comment]
Looks good to me.

**Pull request merged**
